# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    pip install pytest
    py.test -W ignore
  displayName: 'Test with pytest'

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
- cron: "0 11 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
